FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json ./
RUN npm install -g pnpm && pnpm install

COPY . .

# Build Vite pour prod
RUN pnpm run build

FROM nginx:alpine AS production

# Supprime les fichiers par défaut de Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copie les fichiers build depuis le stage builder
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose le port standard HTTP
EXPOSE 80

# Commande par défaut
CMD ["nginx", "-g", "daemon off;"]

