FROM node:20-alpine

WORKDIR /app

COPY package.json ./
RUN npm install -g pnpm && pnpm install

COPY . .

# Générer le client Prisma
RUN pnpm prisma generate && pnpm run build

# Expose le port de l'API
EXPOSE 3000

# Commande prod
CMD ["sh", "-c", "pnpm prisma migrate deploy && pnpm run start:prod"]
# Assure-toi d'avoir "start" dans package.json pour lancer le serveur prod
