FROM node:20-alpine

WORKDIR /app

COPY package.json ./

RUN npm install -g pnpm && pnpm install

COPY . .

EXPOSE 3000

RUN pnpm prisma generate

CMD ["sh", "-c", "pnpm prisma migrate dev --name init && pnpm run start:dev"]
